#To deploy run:
#   export ssh_prv_key="$(cat ~/.ssh/id_rsa_bitbucket_minicube)" && \
#   export ssh_pub_key="$(cat ~/.ssh/id_rsa_bitbucket_minicube.pub)"  && \
#   export uid="$(id -u $(whoami))" && \
#   export gid="$(id -g $(whoami))" && \
#   docker-compose up

version: "3.7"
services:

  jenkins:
    build: 
      context: .
      dockerfile: jenkins.dockerfile
      args:
        - ssh_prv_key
        - ssh_pub_key
        - uid
        - gid
    image: biovices/jenkins:latest
    ports:
      - "0.0.0.0:50000:50000"
      - "0.0.0.0:8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./scripts:/home/jenkins/scripts
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - yocto
    container_name: jenkins

  yocto:
    build:
      context: .
      dockerfile: yocto.dockerfile
      args:
        - ssh_prv_key
        - ssh_pub_key
        - uid
        - gid
    image: biovices/yocto:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    container_name: yocto

volumes:
  jenkins-data:
    name: jenkins-data
